In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.utils import shuffle

In [2]:
# Fetching data
data = pd.read_csv('drebinAndroidMalwareDetectionDataset.csv')
print(data.shape)
data.head()

(15036, 216)


/home/ipc/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (92) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


transact  onServiceConnected  bindService  attachInterface  \
0         0                   0            0                0   
1         0                   0            0                0   
2         0                   0            0                0   
3         0                   0            0                0   
4         0                   0            0                0   

   ServiceConnection  android.os.Binder  SEND_SMS  \
0                  0                  0         1   
1                  0                  0         1   
2                  0                  0         1   
3                  0                  0         0   
4                  0                  0         0   

   Ljava.lang.Class.getCanonicalName  Ljava.lang.Class.getMethods  \
0                                  0                            0   
1                                  0                            0   
2                                  0                            0   
3                                  0                            0   
4                                  0                            0   

   Ljava.lang.Class.cast  ...  READ_CONTACTS  DEVICE_POWER  HARDWARE_TEST  \
0                      0  ...              0             0              0   
1                      0  ...              0             0              0   
2                      0  ...              0             0              0   
3                      1  ...              0             0              0   
4                      0  ...              0             0              0   

   ACCESS_WIFI_STATE  WRITE_EXTERNAL_STORAGE  ACCESS_FINE_LOCATION  \
0                  0                       1                     0   
1                  0                       1                     0   
2                  0                       0                     0   
3                  1                       1                     1   
4                  1                       0                     1   

   SET_WALLPAPER_HINTS  SET_PREFERRED_APPLICATIONS  WRITE_SECURE_SETTINGS  \
0                    0                           0                      0   
1                    0                           0                      0   
2                    0                           0                      0   
3                    0                           0                      0   
4                    0                           0                      0   

   class  
0      S  
1      S  
2      S  
3      S  
4      S  

[5 rows x 216 columns]

In [3]:
#Checking for null values in the dataset
data[data.columns[215]].isnull().value_counts()

False    15036
Name: class, dtype: int64

In [4]:
# Mark malware - '1' and non as - '0'
data=data.replace(["S","B"],[1,0])
data.rename(columns={'class':'MALWARE'},inplace=True)
print(data.shape)
data.head()

(15036, 216)


transact  onServiceConnected  bindService  attachInterface  \
0         0                   0            0                0   
1         0                   0            0                0   
2         0                   0            0                0   
3         0                   0            0                0   
4         0                   0            0                0   

   ServiceConnection  android.os.Binder  SEND_SMS  \
0                  0                  0         1   
1                  0                  0         1   
2                  0                  0         1   
3                  0                  0         0   
4                  0                  0         0   

   Ljava.lang.Class.getCanonicalName  Ljava.lang.Class.getMethods  \
0                                  0                            0   
1                                  0                            0   
2                                  0                            0   
3                                  0                            0   
4                                  0                            0   

   Ljava.lang.Class.cast  ...  READ_CONTACTS  DEVICE_POWER  HARDWARE_TEST  \
0                      0  ...              0             0              0   
1                      0  ...              0             0              0   
2                      0  ...              0             0              0   
3                      1  ...              0             0              0   
4                      0  ...              0             0              0   

   ACCESS_WIFI_STATE  WRITE_EXTERNAL_STORAGE  ACCESS_FINE_LOCATION  \
0                  0                       1                     0   
1                  0                       1                     0   
2                  0                       0                     0   
3                  1                       1                     1   
4                  1                       0                     1   

   SET_WALLPAPER_HINTS  SET_PREFERRED_APPLICATIONS  WRITE_SECURE_SETTINGS  \
0                    0                           0                      0   
1                    0                           0                      0   
2                    0                           0                      0   
3                    0                           0                      0   
4                    0                           0                      0   

   MALWARE  
0        1  
1        1  
2        1  
3        1  
4        1  

[5 rows x 216 columns]

In [5]:
#Shuffle the dataset
data = shuffle(data)
print(data.shape)
data.head()

(15036, 216)


transact  onServiceConnected  bindService  attachInterface  \
14502         1                   1            1                1   
14729         1                   1            1                1   
11044         1                   1            1                1   
3990          0                   0            0                0   
2464          0                   1            1                0   

       ServiceConnection  android.os.Binder  SEND_SMS  \
14502                  1                  1         0   
14729                  1                  1         0   
11044                  1                  1         0   
3990                   0                  0         0   
2464                   1                  1         0   

       Ljava.lang.Class.getCanonicalName  Ljava.lang.Class.getMethods  \
14502                                  1                            1   
14729                                  0                            1   
11044                                  0                            0   
3990                                   0                            0   
2464                                   0                            0   

       Ljava.lang.Class.cast  ...  READ_CONTACTS  DEVICE_POWER  HARDWARE_TEST  \
14502                      1  ...              0             0              0   
14729                      1  ...              1             0              0   
11044                      0  ...              0             0              0   
3990                       0  ...              0             0              0   
2464                       0  ...              0             0              0   

       ACCESS_WIFI_STATE  WRITE_EXTERNAL_STORAGE  ACCESS_FINE_LOCATION  \
14502                  1                       1                     0   
14729                  0                       1                     1   
11044                  1                       0                     0   
3990                   1                       0                     1   
2464                   0                       1                     0   

       SET_WALLPAPER_HINTS  SET_PREFERRED_APPLICATIONS  WRITE_SECURE_SETTINGS  \
14502                    0                           0                      0   
14729                    0                           0                      0   
11044                    0                           0                      0   
3990                     0                           0                      0   
2464                     0                           0                      0   

       MALWARE  
14502        0  
14729        0  
11044        0  
3990         1  
2464         1  

[5 rows x 216 columns]

In [18]:
X = data.iloc[:, 0:215].values
Y = data.iloc[:, -1].values
print(X.shape)
print(X)
print(Y.shape)
print(Y)

(15036, 215)
[[1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(15036,)
[0 0 0 ... 1 1 0]


In [19]:
#Dividing the data set into 70%training and 30% testing data sets
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.3,random_state=0)

print(X_train.shape)
print(X_train)
print(Y_train.shape)
print(Y_train)
print(X_test.shape)
print(X_test)
print(Y_test.shape)
print(Y_test)

(10525, 215)
[[1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]]
(10525,)
[0 0 0 ... 0 1 1]
(4511, 215)
[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(4511,)
[0 1 0 ... 1 0 0]


In [16]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [20]:
Y_t = np.reshape(Y_train, (-1, 1))
model = gnb.fit(X_train, Y_t)

ValueError: could not convert string to float: '?'