In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.utils import shuffle

In [36]:
# Fetching data
data = pd.read_csv('drebinAndroidMalwareDetectionDataset.csv')
print(data.shape)
data.head()

(15036, 216)


/home/ipc/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (92) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


transact  onServiceConnected  bindService  attachInterface  \
0         0                   0            0                0   
1         0                   0            0                0   
2         0                   0            0                0   
3         0                   0            0                0   
4         0                   0            0                0   

   ServiceConnection  android.os.Binder  SEND_SMS  \
0                  0                  0         1   
1                  0                  0         1   
2                  0                  0         1   
3                  0                  0         0   
4                  0                  0         0   

   Ljava.lang.Class.getCanonicalName  Ljava.lang.Class.getMethods  \
0                                  0                            0   
1                                  0                            0   
2                                  0                            0   
3                                  0                            0   
4                                  0                            0   

   Ljava.lang.Class.cast  ...  READ_CONTACTS  DEVICE_POWER  HARDWARE_TEST  \
0                      0  ...              0             0              0   
1                      0  ...              0             0              0   
2                      0  ...              0             0              0   
3                      1  ...              0             0              0   
4                      0  ...              0             0              0   

   ACCESS_WIFI_STATE  WRITE_EXTERNAL_STORAGE  ACCESS_FINE_LOCATION  \
0                  0                       1                     0   
1                  0                       1                     0   
2                  0                       0                     0   
3                  1                       1                     1   
4                  1                       0                     1   

   SET_WALLPAPER_HINTS  SET_PREFERRED_APPLICATIONS  WRITE_SECURE_SETTINGS  \
0                    0                           0                      0   
1                    0                           0                      0   
2                    0                           0                      0   
3                    0                           0                      0   
4                    0                           0                      0   

   class  
0      S  
1      S  
2      S  
3      S  
4      S  

[5 rows x 216 columns]

In [37]:
#Checking for null values in the dataset
data[data.columns[215]].isnull().value_counts()

False    15036
Name: class, dtype: int64

In [38]:
# Mark malware - '1' and non as - '0'
data=data.replace(["S","B"],[1,0])
data.rename(columns={'class':'MALWARE'},inplace=True)
print(data.shape)
data.head()

(15036, 216)


transact  onServiceConnected  bindService  attachInterface  \
0         0                   0            0                0   
1         0                   0            0                0   
2         0                   0            0                0   
3         0                   0            0                0   
4         0                   0            0                0   

   ServiceConnection  android.os.Binder  SEND_SMS  \
0                  0                  0         1   
1                  0                  0         1   
2                  0                  0         1   
3                  0                  0         0   
4                  0                  0         0   

   Ljava.lang.Class.getCanonicalName  Ljava.lang.Class.getMethods  \
0                                  0                            0   
1                                  0                            0   
2                                  0                            0   
3                                  0                            0   
4                                  0                            0   

   Ljava.lang.Class.cast  ...  READ_CONTACTS  DEVICE_POWER  HARDWARE_TEST  \
0                      0  ...              0             0              0   
1                      0  ...              0             0              0   
2                      0  ...              0             0              0   
3                      1  ...              0             0              0   
4                      0  ...              0             0              0   

   ACCESS_WIFI_STATE  WRITE_EXTERNAL_STORAGE  ACCESS_FINE_LOCATION  \
0                  0                       1                     0   
1                  0                       1                     0   
2                  0                       0                     0   
3                  1                       1                     1   
4                  1                       0                     1   

   SET_WALLPAPER_HINTS  SET_PREFERRED_APPLICATIONS  WRITE_SECURE_SETTINGS  \
0                    0                           0                      0   
1                    0                           0                      0   
2                    0                           0                      0   
3                    0                           0                      0   
4                    0                           0                      0   

   MALWARE  
0        1  
1        1  
2        1  
3        1  
4        1  

[5 rows x 216 columns]

In [6]:
#Shuffle the dataset
data = shuffle(data)
print(data.shape)
data.head()

(15036, 216)


transact  onServiceConnected  bindService  attachInterface  \
6770          1                   1            1                1   
13848         1                   1            1                1   
2569          0                   0            0                0   
2825          0                   0            0                0   
12364         1                   1            1                1   

       ServiceConnection  android.os.Binder  SEND_SMS  \
6770                   1                  1         0   
13848                  1                  1         0   
2569                   0                  0         1   
2825                   0                  0         0   
12364                  1                  1         0   

       Ljava.lang.Class.getCanonicalName  Ljava.lang.Class.getMethods  \
6770                                   1                            1   
13848                                  1                            1   
2569                                   0                            0   
2825                                   0                            0   
12364                                  1                            1   

       Ljava.lang.Class.cast  ...  READ_CONTACTS  DEVICE_POWER  HARDWARE_TEST  \
6770                       1  ...              0             0              0   
13848                      1  ...              1             0              0   
2569                       0  ...              0             1              0   
2825                       0  ...              0             1              0   
12364                      1  ...              0             0              0   

       ACCESS_WIFI_STATE  WRITE_EXTERNAL_STORAGE  ACCESS_FINE_LOCATION  \
6770                   1                       0                     0   
13848                  1                       1                     1   
2569                   1                       1                     0   
2825                   1                       1                     0   
12364                  1                       1                     0   

       SET_WALLPAPER_HINTS  SET_PREFERRED_APPLICATIONS  WRITE_SECURE_SETTINGS  \
6770                     0                           0                      0   
13848                    0                           0                      0   
2569                     0                           0                      1   
2825                     0                           0                      1   
12364                    0                           0                      0   

       MALWARE  
6770         0  
13848        0  
2569         1  
2825         1  
12364        0  

[5 rows x 216 columns]

In [7]:
X = data.iloc[:, 0:215].values
Y = data.iloc[:, -1].values
print(X.shape)
print(X)
print(Y.shape)
print(Y)

(15036, 215)
[[1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 1]
 [0 0 0 ... 0 0 0]]
(15036,)
[0 0 1 ... 0 0 1]


In [8]:
#Dividing the data set into 70% training and 30% testing data sets
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.3,random_state=0)

print('X_train- ',X_train.shape)
print(X_train)
print('Y_train- ',Y_train.shape)
print(Y_train)
print('X_test- ',X_test.shape)
print(X_test)
print('Y_test- ',Y_test.shape)
print(Y_test)

X_train-  (10525, 215)
[[1 0 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]]
Y_train-  (10525,)
[0 0 0 ... 1 1 0]
X_test-  (4511, 215)
[[1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Y_test-  (4511,)
[0 0 0 ... 0 0 0]


In [31]:
selected_features = []
myFile = open("rf.txt", "r")
for myLine in myFile:
    selected_features.append(int(myLine))
print(selected_features)    

[1, 3, 4]


In [35]:
#Working with first 15 features
X = data.iloc[:, selected_features].values
Y = data.iloc[:, -1].values
print(X.shape)
print(X)
print(Y.shape)
print(Y)

(15036, 3)
[[1 1 1]
 [1 1 1]
 [0 0 0]
 ...
 [1 1 1]
 [1 1 1]
 [0 0 0]]
(15036,)
[0 0 1 ... 0 0 1]
